uppercase p_tag env + remove extra lines

diff --git a/.github/workflows/build-firehose-version.yml b/.github/workflows/build-firehose-version.yml
--- a/.github/workflows/build-firehose-version.yml
+++ b/.github/workflows/build-firehose-version.yml
@@ -18,7 +18,7 @@ on:
         default: false
 
 env:
-  p_tag: p-${{ inputs.tag }}-fh
+  P_TAG: p-${{ inputs.tag }}-fh
 
 jobs:
   tendermint-sdk-fh:
@@ -39,14 +39,14 @@ jobs:
         run: |
           git fetch tendermint refs/tags/${{ inputs.tag }}:refs/tags/tendermint_${{ inputs.tag }} --no-tags
           git fetch gp refs/tags/${{ inputs.fh-tag }}:refs/tags/gp_${{ inputs.fh-tag }} --no-tags
-          git fetch origin 'refs/tags/${{ env.p_tag }}:refs/tags/${{ env.p_tag }}' || echo ""
+          git fetch origin 'refs/tags/${{ env.P_TAG }}:refs/tags/${{ env.P_TAG }}' || echo ""
 
           echo "tags=$(git tag -l | tr '\n' ' ')" >> $GITHUB_ENV
 
-      - if: contains(env.tags, env.p_tag)
+      - if: contains(env.tags, env.P_TAG)
         name: exit if tag already exists
         run: |
-          echo "::error::Tag: $p_tag already exists"
+          echo "::error::Tag: $P_TAG already exists"
           exit 1
 
       - name: print commit diff
@@ -68,12 +68,12 @@ jobs:
           if [[ '${{ steps.fetch_commits.outputs.commits }}' != '' ]]; then
             git cherry-pick ${{ steps.fetch_commits.outputs.commits }}
           else
-            echo "::warning title=No commit diff::No commit difference b/w tags; pushing tag ${{ env.p_tag }} which is identical to tendermint/${{ inputs.tag }}"
+            echo "::warning title=No commit diff::No commit difference b/w tags; pushing tag ${{ env.P_TAG }} which is identical to tendermint/${{ inputs.tag }}"
           fi
-          git tag ${{ env.p_tag }}
-          git push origin refs/tags/${{ env.p_tag }}
+          git tag ${{ env.P_TAG }}
+          git push origin refs/tags/${{ env.P_TAG }}
 
-      - if: failure() && !inputs.dryrun && !contains(env.tags, env.p_tag)
+      - if: failure() && !inputs.dryrun && !contains(env.tags, env.P_TAG)
         name: 'print manual steps'
         run: |
           STEPS=$(cat << EOF
@@ -85,20 +85,18 @@ jobs:
           > git fetch tendermint refs/tags/${{ inputs.tag }}:refs/tags/tendermint_${{ inputs.tag }} --no-tags
           > git fetch gp refs/tags/${{ inputs.fh-tag }}:refs/tags/gp_${{ inputs.fh-tag }} --no-tags
           
-          => Check commit
+          => Check commit diff
           > git log tendermint_${{ inputs.tag }}..gp_${{ inputs.fh-tag }} --pretty='%h | %s [%an]'
           
           => Apply commits and create new tag
           > git checkout tendermint_${{ inputs.tag }}
           > git cherry-pick $(git log tendermint_${{ inputs.tag }}..gp_${{ inputs.fh-tag }} --pretty="%H" --reverse | tr '\n' ' ')
-          > git tag ${{ env.p_tag }}
-          > git push origin refs/tags/${{ env.p_tag }}
+          > git tag ${{ env.P_TAG }}
+          > git push origin refs/tags/${{ env.P_TAG }}
           EOF
           )
-
           STEPS="${STEPS//'%'/'%25'}"
           STEPS="${STEPS//$'\n'/'%0A'}"
           STEPS="${STEPS//$'\r'/'%0D'}"
-
           echo "::notice title=Manually do it?::$STEPS"
           
